language: rust
rust:
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: beta
  fast_finish: true
  include:
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: nightly
  - env: TARGET=x86_64-pc-windows-msvc
    rust: nightly
  - env: TARGET=x86_64-apple-darwin
    rust: nightly
  - env: TARGET=aarch64-unknown-linux-gnu
    rust: nightly
  - env: TARGET=x86_64-unknown-freebsd
    rust: nightly
  - env: TARGET=aarch64-linux-android
    rust: nightly
  - env: TARGET=x86_64-unknown-cloudabi
    rust: nightly
  - env: TARGET=powerpc-unknown-linux-gnu
    rust: nightly
    