[package]
name = "bcrypt"
version = "0.1.0"
authors = ["Mitchell Berry <mitchellberry@protonmail.com>"]

[dependencies]
blowfish = { version = "0.3.0", features = ["bcrypt"] }
base64 = "0.9.3"
rand = "0.5.5"
block-modes = "0.2.0"
byte-tools = "0.3.0"